workspace:
  base: /scablo
  path: src/github.com/razem-io/scablo

pipeline:
  build:
    image: hseeberger/scala-sbt:11.0.9.1_1.4.6_2.11.12
    commands:
    - sbt dist
  github_release:
    image: plugins/github-release
    secrets: [ github_release_api_key ]
    files:
    - target/universal/scablo.sbt
    checksum:
    - sha512
    when:
      event: tag